/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus100(input: number): number
export declare function studioPluginsPath(): string
export declare function studioContentPath(): string
